name:  Run Responsive playwright tests

on:
  push:
  pull_request:

jobs:
  build-test-metatags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm ci
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: Run tests
        env:
          PLAYWRIGHT_CLI_EXIT_ON_FIRST_FAILURE: '1'
        run: npx playwright test tests/loadSpeed.spec.js --config=playwright.config.js || echo "tests_failed=true" >> $GITHUB_ENV

      - name: Print tests_failed
        run: echo "tests_failed=$tests_failed"
  

      - name: Install jq
        run: sudo apt-get install jq

     
      - name: Archive Lighthouse report, videos, and screenshots
        if: env.tests_failed == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: test-artifacts
          path: |
            lighthouse-report.json
            test-results/
            **/*.mp4
            **/*.png
      - name: Exit with failure if tests failed
        if: env.tests_failed == 'true'
        run: exit 1

   