name:  Run tags playwright tests

on:
  push:
  pull_request:

jobs:
  build-test-metatags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm ci
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: Run tests
        run: npx playwright test tests/metaTags.spec.js --config=playwright.config.js || exit 0

  

      - name: Install jq
        run: sudo apt-get install jq

      - name: Archive Lighthouse report, videos, and screenshots
        uses: actions/upload-artifact@v2
        with:
          name: test-artifacts
          path: |
            lighthouse-report.json
            test-results/
            **/*.mp4
            **/*.png
