name: Build and Test Docker Image

on:
  push:
  pull_request:

  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm ci
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: Setup XVFB
        run: sudo apt-get install -y xvfb
      - name: Run tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npx playwright test
S
      - name: Run Lighthouse tests
        run: npx playwright test tests/lighthouse.test.js
      - name: Install jq
        run: sudo apt-get install jq
      - name: Archive Lighthouse report, videos, and screenshots
        uses: actions/upload-artifact@v2
        with:
          name: test-artifacts
          path: |
            lighthouse-report.json
            test-results/
