name: Build and Test Docker Image

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Setup Playwright
        uses: microsoft/playwright-github-action@v1

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run tests
        run: xvfb-run --auto-servernum --server-args='-screen 0 1280x1024x24' npx playwright test

      - name: Install jq
        run: sudo apt-get install jq

      - name: Archive Lighthouse report, videos, and screenshots
        run: |
          npx lighthouse http://localhost:3000/ --output json --output-path lighthouse-report.json --only-categories=performance
          mkdir test-results
          cp -r test-results/* test-results/
        uses: actions/upload-artifact@v2
        with:
          name: test-artifacts
          path: |
            lighthouse-report.json
            test-results/
