name: Validate HTML and CSS

on:
  push:

jobs:
  w3c-validation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Validate HTML and CSS
      uses: validator/validator-action@v3
      with:
        files: "index.html styles.css"